project:
  type: website

website:
  sidebar:
    style: "floating"
    subtitle: "directory"
    contents:
      - section: "Reading"
      - section: "Writing"
      - section: "Projects"
  title: "AHRR"
  search: false
  navbar:
    right:
      - icon: github
        href: https://github.com/andryramorasata
        aria-label: AHRR GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/andry-ramorasata/
        aria-label: Andry Ranto LinkedIn 
      - icon: twitter
        href: https://twitter.com/andryramorasata
        aria-label: AHRR Twitter




format:
  html:
    theme: 
      light: cosmo
      dark: cosmo
    toc: true
    



